name: '532'
channels:
    - conda-forge
    - defaults
dependencies:
    - python=3.11.*
    - ipykernel=6.29.*
    - altair-all=5.5.*
    - dash=2.18.*
    - dash-bootstrap-components=1.7.*
    - plotly=6.0.*
    - tabulate=0.9.*
    - lxml=5.3.*
    - r-base=4.4.*
    - r-tidyverse=2.0.*
    - r-shiny=1.10.*
    - r-languageserver=0.3.*
    - r-plotly=4.10.*
    - geopandas=1.0.*
    - pyproj=3.7.*
    - pandas=2.2.*
    - requests=2.32.*
    - gunicorn=23.0.*
    - pip=25.0.*
    - pip:
        - dash-vega-components=0.11.*
