name: '532'
channels:
    - conda-forge
    - defaults
dependencies:
    - python=3.11
    - ipykernel
    - altair-all
    - dash
    - dash-bootstrap-components
    - plotly
    - tabulate  # df.to_markdown()
    - lxml  # pd.read_html()
    - r-base
    - r-tidyverse
    - r-shiny
    - r-languageserver
    - r-plotly
    - geopandas  # Needed for geospatial operations
    - pyproj  # Required for spatial projections
    - pandas
    - requests
    - gunicorn  # Needed for Render deployment
    - pip
    - pyarrow
    - pip:
        - dash-vega-components
